msan: master - no OQGRAPH due to boost compile error
In file included from /source/storage/oqgraph/graphcore.cc:28:
In file included from /source/storage/oqgraph/graphcore-graph.h:28:
In file included from /source/storage/oqgraph/oqgraph_shim.h:28:
In file included from /source/storage/oqgraph/oqgraph_thunk.h:36:
In file included from /usr/include/boost/unordered_map.hpp:17:
In file included from /usr/include/boost/unordered/unordered_map.hpp:18:
In file included from /usr/include/boost/functional/hash.hpp:6:
/usr/include/boost/container_hash/hash.hpp:131:33: error: no template named 'unary_function' in namespace 'std'; did you mean '__unary_function'?
  131 |         struct hash_base : std::unary_function<T, std::size_t> {};
      |                            ~~~~~^
/usr/lib/llvm-19/bin/../include/c++/v1/__functional/unary_function.h:46:1: note: '__unary_function' declared here
   46 | using __unary_function = __unary_function_keep_layout_base<_Arg, _Result>;
      | ^
1 error generated.
[421/1048] Building CXX object storage/perfschema/CMakeFiles/perfschema.dir/pfs_con_slice.cc.o