Make version_name from os_info actually be useful for searching the RPM repo on {archive/mirror}.mariadb.org
Exception: centos >= 9 which should be sorted out! (relative path on mirrors centos/$version/$platform)

Build_arch is used as $arch in bash_lib.sh, rpm_setup_mariadb_mirror{} to calculate mirror/archive URL.