Pin twisted version
New twisted version gives:
  builtins.AttributeError: Requirements are not satisfied for
  buildbot.util:renderer: The 'zope-interface>=5' distribution was not
  found and is required by Twisted