Need to refresh subscription to use rhel repo
See:
https://access.redhat.com/discussions/3030711?tour=8

Error was:
Red Hat Enterprise Linux 8 for ARM 64 - BaseOS  201  B/s | 357  B     00:01
Errors during downloading metadata for repository 'rhel-8-for-aarch64-baseos-rpms':
  - Status code: 403 for https://cdn.redhat.com/content/dist/rhel8/8/aarch64/baseos/os/repodata/repomd.xml (IP: 2.18.220.251)
Error: Failed to download metadata for repo 'rhel-8-for-aarch64-baseos-rpms': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried