MDBF-933 - DockerLatentWorker containers name not unique
Buildbot calculate the container name on a worker host
based on the sha of the master name.

If the master name is the same between dev / prod, which is true
at this moment (both environments running in containers),
then when the same builder runs on the same host on both environments
a conflict will occur causing one of the builds to fail and retry.

Error: The container name "/buildbot-hz-bbw1-docker-tarball-debian-12-15cc21" is already in use by container
This is an error on the development environment when a build << tarball-docker >> was already running in production on hz-bbw1.

Sometimes builds get stuck in "Preparing worker" state and Production is affected.
This is why this patch is important, because we can impact Production during our tests in buildbot.dev.mariadb.org